---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  host: 127.0.0.1
  encoding: utf8
  database: twitterart_db
  username: root
  password: 
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: twitterart_test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: twitterart_db
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults